services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=obsci
      - DOCKER_INFLUXDB_INIT_PASSWORD=obsci123
      - DOCKER_INFLUXDB_INIT_ORG=obsci
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=super-secret-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
        - obsci-net

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    depends_on:
      - influxdb
      - http-mock
#      - snmp-mock
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - obsci-net

  http-mock:
    build: ./http-server
    container_name: http-mock
    ports:
      - "5000:5000"
    networks:
      - obsci-net

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - influxdb
    networks:
      - obsci-net


volumes:
  influxdb_data:
  grafana_data:

networks:
  obsci-net:
    name: obsci-net
